server:
  port: 8195
  forward-headers-strategy: framework   # 🔥 indispensable pour transférer Authorization

spring:
  application:
    name: api_gateway

  cloud:
    gateway:
      default-filters:
        - TokenRelay                    # 🔥 TRANSFÈRE le token aux microservices
        - RemoveRequestHeader=Cookie    # 🔒 évite les conflits avec Keycloak

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        # ---- AUTH service (public) ----
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        # ---- CATALOGUE service (protégé) ----
        - id: catalogue-service
          uri: http://localhost:8190
          predicates:
            - Path=/api/catalogue/**

        # ---- PANIER service (protégé) ----
        - id: panier-service
          uri: lb://grp8-panier-service
          predicates:
            - Path=/api/paniers/**

        # ---- PAYMENT service (protégé) ----
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payment/**

        # ---- DEMANDE service (protégé) ----
        - id: demande-service
          uri: lb://demande-service
          predicates:
            - Path=/api/demandes/**

        # ---- UPLOADS (PUBLIC) ----
        - id: catalogue-static-uploads
          uri: http://localhost:8084
          predicates:
            - Path=/uploads/**
          filters:
            - PreserveHostHeader

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/myrealm

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8196/eureka