spring.application.name=Demande Service
spring.datasource.url=jdbc:postgresql://ep-delicate-rice-a89bnyyp-pooler.eastus2.azure.neon.tech:5432/grp8_demande_db
spring.datasource.username=neondb_owner
spring.datasource.password=npg_YSBE1HXKTzV3
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
file.upload-dir=uploads/   # dossier relatif à côté du JAR
uploadDir=${user.dir}/uploads
server.port=8085