spring.application.name=authentification_service

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/Auth-DB
spring.datasource.username=postgres
spring.datasource.password=tajidi180903
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.servlet.multipart.enabled=true

# Keycloak realm configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/myrealm
