server:
  port: 8081

spring:
  application:
    name: gr8_authentification_service

  datasource:
    url: jdbc:postgresql://localhost:5432/grp8_catalogue_db
    username: postgres
    password: 11aminalina
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/myrealm
          # jwk-set-uri could also be used:
          # jwk-set-uri: http://localhost:8080/realms/myrealm/protocol/openid-connect/certs

app:
  keycloak:
    admin:
      clientId: backend
      clientSecret: NEPnUB9mBcwReLXDdrOeABtbjw4HCAIG
    realm: myrealm
    serverUrl: http://localhost:8080
 
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8196/eureka